### ISSUE TITLE
Does this lib use Runtime IL Generation

### ISSUE THREAD

**Issue by pha3z** [MightyOrm/Mighty#13]
I don't see a dependency on System.Reflection.Emit listed anywhere. Just want to make sure I'm not missing it.

I'm looking for an ORM that will be compatible with Unity Game Engine, which doesn't support Reflection.Emit.

**Comment by mikebeaton** [comment]
No, unlike Dapper, it doesn't use IL generation. (So its inner loop can't be as fast as Dapper's, but it is as fast as Massive and should be fine for most applications.)

I don't know for sure that's it is compatible with Unity, I haven't tested it, but I don't know of any reason why not.

Feel free to open a new issue if you do find any incompatibilities.
