### ISSUE TITLE
Add samples to project

### ISSUE THREAD

**Issue by brunopbarrote** [MightyOrm/Mighty#14]
Hello!

I've really liked Mighty, i'll start testing before use on my projects, but would be really nice for me and others, add some samples to repo, showing the most basic scenarios.

**Comment by mikebeaton** [comment]
Have you seen the docs at [https://mightyorm.github.io/Mighty/](https://mightyorm.github.io/Mighty/) ? The idea is that those should be enough to started with?

**Comment by mikebeaton** [comment]
Feel free to give me a shout by commenting again here if the samples don't seem enough, or it was hard to find them.
