### ISSUE TITLE
ExecuteMultipleFromProcedure from documentation doesn't exist

### ISSUE THREAD

**Issue by M0dusFRee** [MightyOrm/Mighty#22]
Hi!

I'm testing "multiple result sets" example but ExecuteMultipleFromProcedure method doesn't exist.

Great job, MightyORM is amazing. Thank you.

**Comment by mikebeaton** [comment]
That's a typo in [the docs](https://mightyorm.github.io/Mighty/docs/multiple-resultsets.html). It should be `QueryMultipleFromProcedure` - shout if there's any problems with that. Thanks for spotting.

> Great job, MightyORM is amazing. Thank you.

Thanks! 😊

**Comment by mikebeaton** [comment]
Thanks for Closing & glad to know it's all working okay. Actually I'll reopen & keep this open just for now, to remind me to update the docs asap!

**Comment by mikebeaton** [comment]
Okay, [docs](https://mightyorm.github.io/Mighty/docs/multiple-resultsets.html) now updated by d1ee548
