### ISSUE TITLE
Potential Initialization race condition?

### ISSUE THREAD

**Issue by Kritner** [MightyOrm/Mighty#25]
I'm running an API through a sort of load testing scenario and encountering an issue around mighty orm, here's the stack trace:

```
System.ArgumentException: An item with the same key has already been added. Key: Mighty.DataContracts.DataContractKey
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Mighty.DataContracts.DataContractStore.Get(Boolean IsGeneric, Type type, String columns, SqlNamingMapper mapper)
   at Mighty.MightyOrm`1.Init(String xconnectionString, String tableName, String primaryKeys, String sequence, String columns, Validator xvalidator, SqlNamingMapper xmapper, DataProfiler xprofiler, ConnectionProvider connectionProvider)
   at Mighty.MightyOrm`1..ctor(String connectionString, String table, String primaryKeys, String sequence, String columns, Validator validator, SqlNamingMapper mapper, DataProfiler profiler, ConnectionProvider connectionProvider)
```

The above occurs if I have freshly started my API, with no calls having occurred that would have created a `MightyOrm` connection, then hitting an endpoint that does create a `MightyOrm` connection from 20 separate requests more or less simultaneously.

The same does not seem to occur, at least in a reproduceable manner, if I have previously opened a connection using MightyOrm on an application run.

**Comment by MikeBeaton** [comment]
I _think_ this is not the latest version of Mighty. Can you double check
that you're using 3.1.2?

I had similar issues in my own 'dog fooding' (as I think they say!) project
just recently, and made a couple of changes; in particular I updated two
instances of `Dictionary`, which could be written (not just read) in
different threads, to `ConcurrentDictionary` and even more specifically I
updated the `Dictionary.Add` call which seems to be what is failing for you
to a `ConcurrentDictionary.GetOrAdd` (i.e. ~ add if not already present).

Could you let me know which version you're on, and whether updating to
3.1.2 (if you're not already on it) fixes the problem?

>

**Comment by mikebeaton** [comment]
I _think_ this is not the latest version of Mighty. Can you double check that you're using 3.1.2?

I had similar issues in my own 'dog fooding' (as I think they say!) project just recently, and made a couple of changes; in particular I [updated](https://github.com/MightyOrm/Mighty/blob/master/CHANGELOG.md) two instances of `Dictionary`, which could be written (not just read) in different threads, to `ConcurrentDictionary` and even more specifically I updated the `Dictionary.Add` call which seems to be what is failing for you to a `ConcurrentDictionary.GetOrAdd` (i.e. ~ add if not already present).

Could you let me know which version you're on, and whether updating to [3.1.2](https://www.nuget.org/packages/Mighty) (if you're not already on it) fixes the problem?

**Comment by Kritner** [comment]
it did seem to be because I was on the version prior to 3.1.2, I just tried several times to reproduce on the latest and am unable, thanks!
