### ISSUE TITLE
.net framework 4.x ConnectionStrings provider name

### ISSUE THREAD

**Issue by susahin80** [MightyOrm/Mighty#39]
I used the connection string in app.config like this in .net framework 4.x putting the ProviderName inside te connectionString attribute.

`    <add name="ORACLE" connectionString="User Id=aaa;Password=bbb;Data Source=ccc;ProviderName=Oracle.ManagedDataAccess.Client" />`

In the code I have:
`      private static readonly string oracleConnection = ConfigurationManager.ConnectionStrings["ORACLE"].ConnectionString;`
and use it like this with no problem:
` var db = new MightyOrm<Summary>(oracleConnection);      `

Then I realized  in the [docs ](https://mightyorm.github.io/Mighty/docs/creating-instances-of-mighty.html#net-framework) that I can also use just the connection name.  But when I tried like this, it gave this error: System.InvalidOperationException: 'Unknown database provider: '
` var db = new MightyOrm<Summary>("ORACLE");      `

To be able to make it work, I had to make the following change in the connection string: (moved the provider name in connectionString to the providerName attribute.

`    <add name="ORACLE" connectionString="User Id=aaa;Password=bbb;Data Source=ccc" providerName="Oracle.ManagedDataAccess.Client"/>`

I just wondered if this is a normal behaviour.

**Comment by mikebeaton** [comment]
Yes, it is normal behaviour - that is the correct location for the provider name within the `connectionStrings` section of a .NET Framework .config file.

It is noted that my decision to allow putting the provider name inside the connection string (which is a feature unique to Mighty, which I thought might ease the transition from .NET Framework to .NET Core) continues to confuse... just about everybody, and is being revisited as and when I get a chance to work on the next major release.

But for now, yes, assuming everything's working for you, that is normal, documented behaviour and what I would have expected you to have to do to get that to work.
