### ISSUE TITLE
Need help with code 

### ISSUE THREAD

**Issue by kulwantshimla** [MightyOrm/Mighty#40]
I am a newbee to C#. I have been using  Web Matrix but now I am trying dot net Core Blazor where webmatrix  is not supported.
Luckily I have found Mighty but I need some help with some errors marked in the jpg below.
  
![image](https://user-images.githubusercontent.com/6640620/128840751-efea3d85-ae2a-4fd9-81a3-11477e0e53f4.png)

**Comment by mikebeaton** [comment]
When creating support issues - here or anywhere else - please do not post code as images. E.g. if I want to try out what you've entered, I have to re-type it myself, or OCR it, neither or which are at all convenient. Post code as text (preferably using GitHub markdown code formatting commands).

But:

 - You do not need to use `static` to use Mighty.
 - I think you want `db.All("ID < @0", args: 5);`
 - And `db.All(new { Title = "ABC TEST" });`

**Comment by kulwantshimla** [comment]
Thank You  Sir!

In future I shall make sure to post code in text only.

I really appreciate your response.

Thank You!
