### ISSUE TITLE
Update Question - @MikeBeaton

### ISSUE THREAD

**Issue by garrjo** [MightyOrm/Mighty#5]
First, Love MightyOrm;  I may have found a bug, or I am missing a point on the Update; on Massive the Update feature allows us to include where: args: funcationality and we do not have this on Mighty...does the Update method only allow object passing because, it is expecting the Filter/where condition to be a part of the object?

Is this different than what Massive is doing; as I have never used Massive like this and may have been doing it wrong all this time.

**Comment by garrjo** [comment]
Nevermind - i see you migrated to updateUsing

**Comment by mikebeaton** [comment]
Yep, I switched to `UpdateUsing` instead of the previous overloads of `Update` for this use-case. Partly so that in Mighty you can now `Update(item1, item2, ...)` to update multiple items based on their own primary key if you want.

**Comment by garrjo** [comment]
Yes, I think this is a great change and can see the benefits of doing it this way.

**Comment by garrjo** [comment]
I am using he UpdateUsing 
`
var update_obj = new { Completed = intStatus };
var update = tbl.UpdateUsing(update_obj, where:"ActivityID=@0",args:Convert.ToInt32(activityId));
`

Error
`
            <p>The server encountered an error processing the request. The exception message is 'Cannot implicitly convert type 'System.Dynamic.ExpandoObject' to 'int''. See server logs for more details. The exception stack trace is: </p>
            <p>   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Mighty.MightyOrm`1.UpdateUsing(Object partialItem, String where, DbConnection connection, Object[] args)
   at Mighty.MightyOrm`1.UpdateUsing(Object partialItem, String where, Object[] args)
   at domain.UnifiedService.SweepService.UpdateStatus(String activityId) in {file} line 220
   at domain.UnifiedService.SweepService.GetLiveActivityStatus(String activity_id) in  {file} line 179
   at SyncInvokeGetLiveActivityStatus(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)</p>`

It seems as though, the passed value when not typed matched string vs int; it definately has a problem...or I could very well be using this incorrectly.  Let me know your thoughts.

**Comment by mikebeaton** [comment]
I've just done a few quick tests, and I think the problem is with the call itself and not with anything inside of Mighty. C# is struggling with the combination of the explicit `args:` specification, along with `Convert.ToInt32()`, along with dynamic objects.

If you remove the explicit `where:` and `args:` parameter names:

```c#
var update = tbl.UpdateUsing(update_obj, "ActivityID=@0", Convert.ToInt32(activityId));
```

I think that might fix it?

You should also be able to do the even simpler:

```c#
var update = tbl.UpdateUsing(update_obj, "ActivityID=@0", activityId);
```

If `activityId` is already an `int` I'd say that is definitely better (simpler, more readable); even if `activityId` is a string containing an integer it will still work, and there is no possibility for SQL injection: in Mighty all parameter values are always passed as true `DbParameter` values and never just interpolated into strings.

---

If you definitely needed the explicit `args:` specification and you definitely need `Convert.ToInt32()` (but I think you don't) then to force C# to understand what you want you would have to do:

```c#
var update = tbl.UpdateUsing(update_obj, where: "ActivityID=@0", args: new object[] { Convert.ToInt32(activityId) });
```

But I think that is overkill!

**Comment by garrjo** [comment]
I like that...and yes, your first example likely answers...

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mikebeaton** [comment]
Cool ... and I think the second example should be fine too? If `activityId` is a string (you didn't say) then a string would get passed as a parameter to the database, but the DB will accept any string which parses as an int for an int parameter anyway.

I guess the idea of Mighty (which is directly the thing which it gets from Massive) is to copy @robconery and leverage the more obscure corners of C# (`params`, `dynamic`, also the fact that 99% of the time `DbParameter`s are very good at setting their own type) to create readable, convenient code - once you get the hang of the patterns for using it!

PS Have you downloaded the [new version](https://www.nuget.org/packages/Mighty), and seen that I've now put up a [docs site](https://mightyorm.github.io/Mighty/)? 😊

**Comment by garrjo** [comment]
activityId is a string and yes, It should have been accepted without a problem * that is if i did the update correctly.  

I have the new version and yes, been looking at the docs; I agree with you 1000% of DbParameter vs any other method of sql code writing (especially inline sql writing..etc).
