### ISSUE TITLE
How to add plugin for new provider?

### ISSUE THREAD

**Issue by sdshaffer** [MightyOrm/Mighty#51]
With the System.Data.SqlClient library being dead/unsupported beyond security updates for a few years now, replaced by Microsoft.Data.SqlClient, I'm trying to add support for the latter locally. Certainly seems like I should be able to do it with the plugin architecture, but I'm not quite getting it.

PluginBase.cs says to subclass the existing plugin for the database (SqlServer in this case) and implement GetProviderFactoryClassName - but you can't do that because the default plugins are internal, not public. The rest of the comment there says to use PluginManager.RegisterPlugin to register your custom plugin (which would just have to implement PluginBase, that's easy enough), but where would that registration actually be done? 

Alternatively it says you could just use your plugin in your own subclass of ConnectionProvider instead of registering it, appears that you'd use it in the Init method. It appears the ProviderFactoryInstance property also needs to be set, and looking at the existing providers they loop back to internal classes and things that depend on the registered plugins. Plus, the ConnectionProvider says you need to both subclass it _and_ register your plugin with the PluginManager. So we're back to that again.

So what's the right way to get this working? Seems like a lot to have to go through to do the equivalent of adding <case "microsoft.data.sqlclient": return "Microsoft.Data.SqlClient.SqlClientFactory";> to SqlServer.cs (I'm completely assuming it will just work), but I would rather use the plugin system as intended instead of having to do my own build of Mighty.

**Comment by mikebeaton** [comment]
[Microsoft.Data.SqlClient](https://www.nuget.org/packages/microsoft.data.sqlclient) support added, in Mighty versions [3.3.0](https://github.com/MightyOrm/Mighty/commit/9e98383be21fda5131dc079fc27c680ac99d4b9c) and [4.0.0-alpha-6](https://github.com/MightyOrm/Mighty/commit/d4f2e92698fa2b6f24658175d099c86d56e3757f) on [NuGet](https://www.nuget.org/packages/Mighty).
